import { cpSync, existsSync, mkdirSync, copyFileSync } from 'node:fs'
import { join } from 'node:path'

import { app, BrowserWindow, dialog, session, shell } from 'electron'

import { HARNESS_URL, HarnessService } from './harness-service.mjs'

const LOCAL_ORIGIN = new URL(HARNESS_URL).origin
app.setName('DeepSeek Harness')
app.setPath('userData', join(app.getPath('appData'), 'DeepSeek Harness'))

let mainWindow = null
let harnessService = null
let quitting = false

function preparePackagedData() {
  const harnessHome = join(app.getPath('userData'), 'harness')
  const defaults = join(process.resourcesPath, 'harness-defaults')
  mkdirSync(harnessHome, { recursive: true })

  const settingsTarget = join(harnessHome, 'settings.yaml')
  const settingsSource = join(defaults, 'settings.yaml')
  if (!existsSync(settingsTarget) && existsSync(settingsSource)) {
    copyFileSync(settingsSource, settingsTarget)
  }

  const presetsSource = join(defaults, '.agent-presets')
  if (existsSync(presetsSource)) {
    cpSync(presetsSource, join(harnessHome, '.agent-presets'), {
      recursive: true,
      force: true,
    })
  }
  return harnessHome
}

function loadingPage(message = '正在启动 DeepSeek Harness…') {
  const safeMessage = message
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
  return `data:text/html;charset=utf-8,${encodeURIComponent(`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width">
<style>
  :root { color-scheme: dark; font-family: Inter, "Microsoft YaHei", sans-serif; }
  body { margin: 0; min-height: 100vh; display: grid; place-items: center; background: #0d0f12; color: #e8e8e8; }
  main { text-align: center; max-width: 680px; padding: 40px; }
  .mark { width: 44px; height: 44px; margin: 0 auto 24px; border: 3px solid #404753; border-top-color: #fff; border-radius: 50%; animation: spin 1s linear infinite; }
  .error .mark { display: none; }
  h1 { font-size: 20px; font-weight: 600; margin: 0 0 12px; }
  p { color: #aab0ba; line-height: 1.7; white-space: pre-wrap; overflow-wrap: anywhere; }
  @keyframes spin { to { transform: rotate(360deg); } }
</style></head><body><main class="${message.startsWith('启动失败') ? 'error' : ''}">
<div class="mark"></div><h1>${message.startsWith('启动失败') ? 'DeepSeek Harness 启动失败' : 'DeepSeek Harness'}</h1>
<p>${safeMessage}</p></main></body></html>`)}`
}

function isAllowedLocalUrl(value) {
  try {
    return new URL(value).origin === LOCAL_ORIGIN
  } catch {
    return false
  }
}

function openExternalUrl(value) {
  try {
    const url = new URL(value)
    if (url.protocol === 'https:' || url.protocol === 'http:') void shell.openExternal(url.href)
  } catch {
    // Ignore invalid URLs generated by page content.
  }
}

function createWindow() {
  const window = new BrowserWindow({
    width: 1380,
    height: 900,
    minWidth: 960,
    minHeight: 640,
    show: false,
    backgroundColor: '#0d0f12',
    title: 'DeepSeek Harness',
    autoHideMenuBar: true,
    webPreferences: {
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webviewTag: false,
    },
  })
  window.once('ready-to-show', () => window.show())
  window.webContents.setWindowOpenHandler(({ url }) => {
    if (isAllowedLocalUrl(url)) void window.loadURL(url)
    else openExternalUrl(url)
    return { action: 'deny' }
  })
  window.webContents.on('will-navigate', (event, url) => {
    if (isAllowedLocalUrl(url) || url.startsWith('data:text/html')) return
    event.preventDefault()
    openExternalUrl(url)
  })
  window.on('closed', () => {
    mainWindow = null
  })
  return window
}

async function startDesktop() {
  mainWindow = createWindow()
  await mainWindow.loadURL(loadingPage())

  const appPath = app.getAppPath()
  const harnessHome = app.isPackaged ? preparePackagedData() : join(appPath, '.dsh')
  const workingDirectory = app.isPackaged
    ? join(app.getPath('documents'), 'DeepSeek Harness Workspace')
    : appPath
  const nodePath = app.isPackaged
    ? join(process.resourcesPath, 'node-runtime', 'node.exe')
    : join(appPath, '.electron-runtime', 'node.exe')

  harnessService = new HarnessService({
    appPath,
    nodePath,
    patchPath: join(appPath, 'electron', 'directory-picker.patch.yml'),
    harnessHome,
    workingDirectory,
  })

  try {
    await harnessService.start()
    await mainWindow.loadURL(HARNESS_URL)
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error)
    await mainWindow.loadURL(loadingPage(`启动失败\n\n${message}\n\n日志目录：${join(harnessHome, 'logs')}`))
    dialog.showErrorBox('DeepSeek Harness 启动失败', message)
  }
}

if (!app.requestSingleInstanceLock()) {
  app.quit()
} else {
  app.enableSandbox()
  app.on('second-instance', () => {
    if (!mainWindow) return
    if (mainWindow.isMinimized()) mainWindow.restore()
    mainWindow.show()
    mainWindow.focus()
  })

  app.whenReady().then(async () => {
    session.defaultSession.setPermissionRequestHandler((_webContents, _permission, callback) => {
      callback(false)
    })
    await startDesktop()
  })

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) void startDesktop()
  })

  app.on('before-quit', () => {
    if (quitting) return
    quitting = true
    harnessService?.stop()
  })

  app.on('window-all-closed', () => app.quit())
}
